completed dom-event-delegation.
david-s-song/m1-0122-code-solutions pull request #54
Opened 2022-03-22 17:46 UTC by david-s-song

https://user-images.githubusercontent.com/90665895/159543227-4585dd0a-5bd3-47df-8d95-a88af9049aac.mov

2022-03-22 20:09 UTC, Zhiwutian requested changes
tiny update

2022-03-22 20:09 UTC, BrettAlbright commented on dom-event-delegation/main.js
> +  if (e.target === 'BUTTON') {
you want to check the `tagName` property here on the target property

2022-03-23 01:28 UTC, david-s-song commented
https://user-images.githubusercontent.com/90665895/159603872-92896dc4-03b8-4c30-8ccc-712b0277e64d.mov

2022-03-23 02:05 UTC, Zhiwutian approved these changes
👍🏼

2022-03-25 02:45 UTC, merged